name: Java CI with Maven and Testcontainers

on:
  push:
    branches:
      - "feature/**"
      - "bugfix/**"
  pull_request:
    branches:
      - "main"

env:
  TESTCONTAINERS_RYUK_DISABLED: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o JDK 21
        uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'temurin'
            cache: maven

      - name: Verificar Docker
        run: docker info

      - name: Rodar Testes com Maven e JaCoCo
        working-directory: ./backend/projetoacer
        run: mvn clean test
        env:
          API_SECURITY_TOKEN_SECRET: ${{ secrets.JWT_SECRET }}
      
      - name: Upload do Relatório de Cobertura
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-cobertura-jacoco
          path: backend/projetoacer/target/site/jacoco/